server:
  port: 8080
qywx:
  application-list:
    - secret: Dqwyy-IFoeH7EP7U2Tb-Gb1A7ksS4IP_cZ5JCu2qbl4
      application-name: customer-contact
  url: https://qyapi.weixin.qq.com
  public-path: cgi-bin
  corp-id: ww36e0a51aab349a7d
