server:
  port: 28986
  servlet:
    context-path: /work-chat
qywx:
  application-list:
    - secret: xxxx
      application-name: customer-contact
    - secret: rrpIreNAFdtJc3cC-zLeURq6J-5xOgohWAiLCwbctSY
      agent-id: 3010084
      application-name: schedule
    - secret: AfjvAed_ulqhK0OqTprDQ6xOSnqaT34ll2LsRe0D2NA
      application-name: address-book
      application-desc: 通讯录
    - secret: hAoTUpLro0bV3q9w1rUiOsMaRnnxlom1tk6zZ9qMIY0
      application-name: check-in
      application-desc: 打卡
    - secret: YOtNFA1HvMkGMj1QdokVSjXVBq7KCEcppHmtfkkfT0I
      application-name: public-telephone
      application-desc: 公费电话
    - secret: Pdc49tNGMYx_oACDIEtxCssxyFk_eSj7t9GtclS7fdg
      application-name: approve
      application-desc: 审批
    - secret: 8MP9pzAWN8XvVO-u96eAwAP5PAab49km2BU5Kctbkzs
      application-name: report
      application-desc: 汇报
    - secret: fchDVYqJ-2A7n3O7MMZSogwwoJyGdtOHgTvffwx0EhY
      application-name: meeting-room
      application-desc: 会议室
    - secret: XuZ_VHKE8ZBClGxMrA47bCG887wU_wBzItbz9SB1Jjg
      application-name: oy
      application-desc: 欧亚-冬冬
      agent-id: 1000010
  url: https://qyapi.weixin.qq.com
  public-path: cgi-bin
  corp-id: ww36e0a51aab349a7d
  callback-list:
    - application-name: address-book
      token: 4pd5Q2GAVKAapyTD0IGLMD7Lngiyx
      encoding-aes-key: QJqvdlS4M4FTPUNqSQrMg3VwNRyBCqTqtNStREy3Ahd
      receive-id: ww36e0a51aab349a7d
    - application-name: schedule
      token: CdEcnaCCdcic
      encoding-aes-key: QJqvdlS4M4FTPUNqSQrMg3VwNRyBCqTqtNStREy3Ahd
      receive-id: ww36e0a51aab349a7d
logging:
  level:
    root: warn
    com.github.shuaidd: debug
