server:
  port: 8080
qywx:
  application-list:
    - secret: xxxx
      application-name: customer-contact
    - secret: xxxx
      agent-id: 3010084
      application-name: schedule
    - secret: xxx
      application-name: address-book
  url: https://qyapi.weixin.qq.com
  public-path: cgi-bin
  corp-id: xxx
logging:
  level:
    root: warn
    com.github.shuaidd: info
