server:
  port: 28986
  servlet:
    context-path: /work-chat
qywx:
  application-list:
    - secret: xxxx
      application-name: customer-contact
    - secret: xxxx
      agent-id: 3010084
      application-name: schedule
    - secret: xxx
      application-name: address-book
      application-desc: 通讯录
    - secret: xxxx
      application-name: check-in
      application-desc: 打卡
    - secret: xxx
      application-name: public-telephone
      application-desc: 公费电话
    - secret: xxx
      application-name: approve
      application-desc: 审批
    - secret: xxx
      application-name: report
      application-desc: 汇报
    - secret: xxxx
      application-name: meeting-room
      application-desc: 会议室
  url: https://qyapi.weixin.qq.com
  public-path: cgi-bin
  corp-id: xxx
logging:
  level:
    root: warn
    com.github.shuaidd: debug
